workflows:
  android-workflow:
    name: Build Android APK
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      node: 18.20.0
      npm: 10.8.2
      vars:
        PACKAGE_MANAGER: npm
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          npx cap sync android
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
